### ISSUE TITLE
synology_srm.http.SynologyApiError: Unknown API error, please check the documentation (error=1002)

### ISSUE THREAD

**Issue by boitier** [gilmrt/srm-exporter#6] opened 2023-10-29 14:47 UTC
Hello,

I have this issue with using this exporter..
My setup : 
Exporter run in docker on Synology
SRM : SRM 1.3.1-9346 Update 7 on RT2600AC

Docker Compose : 
  srm-exporter:
     container_name: srm-exporter
     image: ghcr.io/gilmrt/srm-exporter:latest
     hostname: srm-exporter
     environment:
      TZ: Europe/Paris
      SRM_HOST: *****
      SRM_PORT: 8001
      SRM_USERNAME: admin
      SRM_PASSWORD: *****
      USE_HTTPS: True
      DISABLE_HTTPS_VERIFY: True
      EXPORTER_CACHE_FOR: 0
      EXPORTER_PORT: 9922
      ports:
       - 9922:9922
     network_mode: 'bridge'
     restart: unless-stopped

It cause Err 500 : Internal Error when accessing to /metrics page

Complete log : 
023/10/29 15:02:13,stderr,"synology_srm.http.SynologyApiError: Unknown API error, please check the documentation (error=1002)"
2023/10/29 15:02:13,stderr,    raise SynologyApiError(
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/synology_srm/http.py\", line 179, in call"
2023/10/29 15:02:13,stderr,           ^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    return self.http.call(
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/synology_srm/api/core.py\", line 63, in get_ngfw_traffic"
2023/10/29 15:02:13,stderr,                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    ngfw_traffic = client.core.get_ngfw_traffic(interval=period)
2023/10/29 15:02:13,stderr,"  File \"/app/exporter.py\", line 362, in get_traffic_stats"
2023/10/29 15:02:13,stderr,        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,"    ) = get_traffic_stats(client, mac_to_hostname, mac_to_ip_addr, period)"
2023/10/29 15:02:13,stderr,"  File \"/app/exporter.py\", line 490, in updateResults"
2023/10/29 15:02:13,stderr,           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/flask/app.py\", line 1796, in dispatch_request"
2023/10/29 15:02:13,stderr,         ^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    rv = self.dispatch_request()
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/flask/app.py\", line 1820, in full_dispatch_request"
2023/10/29 15:02:13,stderr,         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    rv = self.handle_user_exception(e)
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/flask/app.py\", line 1822, in full_dispatch_request"
2023/10/29 15:02:13,stderr,               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/10/29 15:02:13,stderr,    response = self.full_dispatch_request()
2023/10/29 15:02:13,stderr,"  File \"/usr/local/lib/python3.11/site-packages/flask/app.py\", line 2525, in wsgi_app"
2023/10/29 15:02:13,stderr,Traceback (most recent call last):
2023/10/29 15:02:13,stderr,ERROR 2023-10-29 15:02:13 Exception on /metrics [GET]
2023/10/29 15:02:07,stderr,INFO 2023-10-29 15:02:07 Total download=12.29 KB Total upload=10.69 KB
2023/10/29 15:01:16,stderr,INFO 2023-10-29 15:01:16 Starting Synology-SRM-Exporter on http://localhost:9922

Do you have this issue ?

Regards.

PAB

**Comment by gilmrt** [comment] 2023-10-30 20:49
> Hello,
> 
> I have this issue with using this exporter.. My setup : Exporter run in docker on Synology SRM : SRM 1.3.1-9346 Update 7 on RT2600AC
> 
> Docker Compose : srm-exporter: container_name: srm-exporter image: ghcr.io/gilmrt/srm-exporter:latest hostname: srm-exporter environment: TZ: Europe/Paris SRM_HOST: ***** SRM_PORT: 8001 SRM_USERNAME: admin SRM_PASSWORD: ***** USE_HTTPS: True DISABLE_HTTPS_VERIFY: True EXPORTER_CACHE_FOR: 0 EXPORTER_PORT: 9922 ports: - 9922:9922 network_mode: 'bridge' restart: unless-stopped
> 
> It cause Err 500 : Internal Error when accessing to /metrics page
> 
> Complete log : 023/10/29 15:02:13,stderr,"synology_srm.http.SynologyApiError: Unknown API error, please check the documentation (error=1002)" 2023/10/29 15:02:13,stderr, raise SynologyApiError( 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/synology_srm/http.py", line 179, in call" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, return self.http.call( 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/synology_srm/api/core.py", line 63, in get_ngfw_traffic" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, ngfw_traffic = client.core.get_ngfw_traffic(interval=period) 2023/10/29 15:02:13,stderr," File "/app/exporter.py", line 362, in get_traffic_stats" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr," ) = get_traffic_stats(client, mac_to_hostname, mac_to_ip_addr, period)" 2023/10/29 15:02:13,stderr," File "/app/exporter.py", line 490, in updateResults" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, rv = self.dispatch_request() 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, rv = self.handle_user_exception(e) 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request" 2023/10/29 15:02:13,stderr, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023/10/29 15:02:13,stderr, response = self.full_dispatch_request() 2023/10/29 15:02:13,stderr," File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app" 2023/10/29 15:02:13,stderr,Traceback (most recent call last): 2023/10/29 15:02:13,stderr,ERROR 2023-10-29 15:02:13 Exception on /metrics [GET] 2023/10/29 15:02:07,stderr,INFO 2023-10-29 15:02:07 Total download=12.29 KB Total upload=10.69 KB 2023/10/29 15:01:16,stderr,INFO 2023-10-29 15:01:16 Starting Synology-SRM-Exporter on http://localhost:9922
> 
> Do you have this issue ?
> 
> Regards.
> 
> PAB

I currently have no problems with my wrx560, let me try to debug it.

**Comment by boitier** [comment] 2023-10-31 20:50
What do you need to help to debug it ?

**Comment by gilmrt** [comment] 2023-11-01 10:09
Can you tell me if you've had your router for more than a month? Or if it's been working for more than 1 month?
I think the error comes from collecting information by period (day, week, month)...
The Synology Router Manager API documentation isn't public, so I can't figure out what error code 1002 means.
Still debugging ...

**Comment by boitier** [comment] 2023-11-01 13:09
I have my router for more than one year ;-)

**Comment by gilmrt** [comment] 2023-11-01 13:50
Can you try the new version ghcr.io/gilmrt/srm-exporter:1.2.0 (or update the latest image) and add PERIODS=live as environment variable in your composition file.
Launch the container, go to metrics ... hope it works for you
The problem seems to be linked to the router model, as I also use SRM version 1.3.1-9346 Update 7 on WRX560 without any problems

**Comment by boitier** [comment] 2023-11-01 14:44
It works great ! many thanks for the fix

**Comment by gilmrt** [comment] 2023-11-01 15:11
Awesome!!!
Now, can you try with PERIODS=live,day,week,month? Just to try to reproduce the error? So I can clarify the error.
Afterwards feel free to use only PERIODS=live and retrieve the history from prometheus instead of retrieving the history data from the SRM router.
Just let me know the result and so I can close the issue with root cause

**Comment by gilmrt** [comment] 2023-11-01 15:40
Awesome!!!
Now, can you try with PERIODS=live,day,week,month? Just to try to reproduce the error? So I can clarify the error.
Afterwards feel free to use only PERIODS=live and retrieve the history from prometheus instead of retrieving the history data from the SRM router.
Just let me know the result and so I can close the issue with root cause

**Comment by boitier** [comment] 2023-11-01 16:05
It works with :
PERIODS: live
or
PERIODS: day
or
PERIODS: week

I does not work with :
PERIODS: live,day,week,month
or
PERIODS: month

With the same error=1002

**Comment by gilmrt** [comment] 2023-11-01 17:03
Issue with `month` period on RT2600AC
Add as known issues in README
Closed

**Closed as completed by gilmrt** 2023-11-01 17:03 UTC
